[package]
name = "spider-rust"
version = "0.1.0"
authors = ["Tosone <i@tosone.cn>"]
edition = "2018"

[dependencies]
rusqlite = { version = "0.26.1", features = ["bundled"] }
serde_json = {version = "1.0.71"}
serde = {version = "1.0.130", features = ["derive"]}
